"""Render the rule registry as the style guide an agent reads.

The guide and the checker come from the same objects, so a rule cannot exist
in one and not the other.
"""

from __future__ import annotations

import textwrap

from .fixers import FIXERS
from .rule import REGISTRY, SECTION_ORDER, Rule

WRAP = 96
BANNER = "<!-- Generated by `styleck docs`. Edit the rules in styleck/, not this file. -->"

HEADER = """# Writing style for math papers

{banner}

These rules cover writing quality only: LaTeX layout, equations, diagrams, and
prose. They say nothing about code.

Most of them are machine-checked. After you edit a `.tex` file a hook runs
`styleck` on it, repairs what is mechanical, and reports the rest back to you
by rule id. Fix what it reports before moving on.

Run it yourself at any time:

```
python -m styleck path/to/paper.tex        # report
python -m styleck --fix path/to/paper.tex  # repair what is mechanical
python -m styleck --concordance the path/to/paper.tex  # inspect every `the`
```

Tags below: **auto-fix** means `--fix` repairs it, so do not hand-edit those.
**judgment** means no checker exists and the rule is on you.
"""

FOOTER = """
## When the checker and your taste disagree

The checker wins on the mechanical rules. If you think a rule is wrong for a
specific line, say so in chat and leave the code alone until you get an answer.
"""


def _tag(rule: Rule) -> str:
    if rule.severity == "manual":
        return "judgment"
    if rule.id in FIXERS:
        return f"{rule.severity}, auto-fix"
    return rule.severity


def _example(marker: str, body: str) -> list[str]:
    if not body:
        return []
    if "\n" in body:
        lines = [f"  {marker}", "", "  ```latex"]
        lines.extend("  " + row for row in body.split("\n"))
        lines.extend(["  ```", ""])
        return lines
    return [f"  {marker} `{body}`"]


def render_rule(rule: Rule) -> list[str]:
    head = f"- **{rule.id}** ({_tag(rule)}) — {rule.summary}"
    lines = textwrap.wrap(head, WRAP, subsequent_indent="  ", break_long_words=False)
    if rule.detail:
        for row in textwrap.wrap(rule.detail, WRAP - 2):
            lines.append(f"  {row}")
    lines.extend(_example("✗", rule.bad))
    lines.extend(_example("✓", rule.good))
    lines.append("")
    return lines


def render() -> str:
    """The complete style guide."""
    out = [HEADER.format(banner=BANNER).rstrip(), ""]
    for section in SECTION_ORDER:
        rules = [r for r in REGISTRY.values() if r.section == section]
        if not rules:
            continue
        out.append(f"## {section}")
        out.append("")
        for rule in sorted(rules, key=lambda r: r.id):
            out.extend(render_rule(rule))
    out.append(FOOTER.strip())
    out.append("")
    return "\n".join(out)


def render_summary() -> str:
    """One line per rule, for a quick reminder mid-session."""
    out = []
    for section in SECTION_ORDER:
        rules = sorted(
            (r for r in REGISTRY.values() if r.section == section),
            key=lambda r: r.id,
        )
        for rule in rules:
            out.append(f"{rule.id}: {rule.summary}")
    return "\n".join(out) + "\n"
