"""Write the generated writing guide into the repos that need it.

Each paper repo keeps its own hand-written claude.md for coding and workflow
rules. The writing rules are not copied into it; they are generated into
`writing-style.md` and pulled in with an `@writing-style.md` import line, so
one edit to the rules reaches every repo and no copy can drift.
"""

from __future__ import annotations

from pathlib import Path

from .docgen import BANNER, render

GUIDE_NAME = "writing-style.md"
CLAUDE_NAME = "claude.md"
IMPORT_LINE = f"@{GUIDE_NAME}"


def is_generated(path: Path) -> bool:
    if not path.is_file():
        return False
    return BANNER in path.read_text(encoding="utf-8", errors="replace")


def imports_guide(claude_md: Path) -> bool:
    if not claude_md.is_file():
        return False
    body = claude_md.read_text(encoding="utf-8", errors="replace")
    return any(line.strip() == IMPORT_LINE for line in body.splitlines())


def sync(targets: list[Path], add_import: bool = False) -> list[tuple[Path, str]]:
    """Write the guide into each target directory.

    Returns one (path, outcome) pair per target. A `writing-style.md` that was
    not generated by this tool is left alone, so nobody loses hand-written notes.
    """
    body = render()
    results = []
    for directory in targets:
        results.append(_sync_one(directory, body, add_import))
    return results


def _sync_one(directory: Path, body: str, add_import: bool) -> tuple[Path, str]:
    path = directory / GUIDE_NAME
    if path.exists() and not is_generated(path):
        return path, "skipped (hand-written)"
    if path.exists() and path.read_text(encoding="utf-8", errors="replace") == body:
        outcome = "unchanged"
    else:
        outcome = "updated" if path.exists() else "created"
        path.write_text(body, encoding="utf-8")

    claude_md = directory / CLAUDE_NAME
    if imports_guide(claude_md):
        return path, outcome
    if add_import and claude_md.is_file():
        _append_import(claude_md)
        return path, f"{outcome} (+import)"
    return path, f"{outcome} (claude.md needs a line: {IMPORT_LINE})"


def _append_import(claude_md: Path) -> None:
    body = claude_md.read_text(encoding="utf-8", errors="replace")
    separator = "" if body.endswith("\n") else "\n"
    claude_md.write_text(f"{body}{separator}\n{IMPORT_LINE}\n", encoding="utf-8")


def find_targets(root: Path) -> list[Path]:
    """Directories under `root` that already carry a claude.md."""
    found = {path.parent for path in root.glob(f"*/{CLAUDE_NAME}")}
    if (root / CLAUDE_NAME).exists():
        found.add(root)
    return sorted(found)
